name: build & run

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: cmake
      run: cmake ./corruption
    - name: make
      run: make

  run:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: cmake
      run: cmake ./corruption
    - name: make
      run: make
    - name: run png-corruption
      run: ./png-corruption --file ./bin/png.png --output ./bin/out.png --info --increment 1
