name: tests

on: [push]

jobs:
  help:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: cmake
      run: cmake ./corruption/corruption
    - name: make
      run: make
    - name: run png-corruption
      run: ./png-corruption -h

  input_and_output:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: cmake
      run: cmake ./corruption
    - name: make
      run: make
    - name: run png-corruption
      run: ./png-corruption -f ./bin/png.png -o ./out.png

  only_input:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: cmake
      run: cmake ./corruption
    - name: make
      run: make
    - name: run png-corruption
      run: ./png-corruption -f ./bin/png.png

  only_output:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: cmake
      run: cmake ./corruption
    - name: make
      run: make
    - name: run png-corruption
      run: ./png-corruption -o ./out.png

  output_and_input:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: cmake
      run: cmake ./corruption
    - name: make
      run: make
    - name: run png-corruption
      run: ./png-corruption -o ./out.png -f ./bin/png.png

  incrementation:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: cmake
      run: cmake ./corruption
    - name: make
      run: make
    - name: run png-corruption
      run: ./png-corruption -f ./bin/png.png -o ./out.png --increment 1

  shifting:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: cmake
      run: cmake ./corruption
    - name: make
      run: make
    - name: run png-corruption
      run: ./png-corruption -f ./bin/png.png -o ./out.png --shift 1

  incrementation_and_shifting:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: cmake
      run: cmake ./corruption
    - name: make
      run: make
    - name: run png-corruption
      run: ./png-corruption -f ./bin/png.png -o ./out.png --increment 1 --shift 1

  shifting_and_incrementation:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: cmake
      run: cmake ./corruption
    - name: make
      run: make
    - name: run png-corruption
      run: ./png-corruption -f ./bin/png.png -o ./out.png --shift 1 --increment 1

